### PR TITLE
mask sensitive information of connection for remote source.

### PR DESCRIPTION
**Pull request by harshkothari410**

### CODE REVIEW

**Comment by harshkothari410** [comment]
@iamigo I tried with encryption SGT and successfully ran collector after modifying couple of things in Refocus-collector.. So this thing is working.

**Comment by iamigo** [comment]
@jgraff2 @harshkothari410 I think we should we update version and do npm publish on refocus-collector with this change, what do you think?

**Comment by harshkothari410** [comment]
For NPM package publish as per my opinion we need to wait for one more PR that fixes integration of refocus and collector related to encryption.

**Comment by harshkothari410** [comment]
I found the issue: 

When collector starts: /v1/collectors/start, Refocus provides response with addedGenerators and in that response we are not getting encryption algorithm as well as in that portion we are not getting decrypt - encrypt version of context variable because we are only doing this process in Heartbeat response not in collector start method. @iamigo @jgraff2 

Its refocus side issue so we can close this PR over here and I will create new story to fix that bug in refocus side. Let me know what you guys think.

**Pull request merged**
